import React, { useState } from 'react';
import { sessionFromRuntime } from './runtime-session';
import { createRoot } from 'react-dom/client';
import { canRenderProtectedShell, sessionMessage, type SessionState, type SessionStatus } from './auth';
import { InstructorAuthoringWorkspace } from './authoring-ui';
import { QuestionAssessmentWorkspace } from './assessment-ui';
import { OrganizationAdminView } from './organization-admin-ui';
import { PersonnelAdminView } from './personnel-admin-ui';
import { GroupDirectoryAdminView } from './group-directory-admin-ui';
import { OperationsAdminView } from './operations-admin-ui';
import { navForRole, type WebRole } from './navigation';
import { defaultScreenFor, screenFor, type ScreenDefinition } from './screens';
import './styles.css';

type ViewState = 'success' | 'loading' | 'empty' | 'error' | 'forbidden' | 'not-found';
const roleLabels: Record<WebRole, string> = { tenant_admin: 'Tenant Admin', instructor: 'Instructor', reviewer: 'Reviewer', learner: 'Learner' };
function SessionPanel({ session, onLogin }: { session: Exclude<SessionState, { status: 'authenticated' }>; onLogin: () => void }) { const copy = sessionMessage(session); const loginAllowed = session.status === 'unauthenticated' || session.status === 'expired'; return <main id="main-content" className="auth-stage"><section className="auth-card" aria-live="polite"><span className="eyebrow">Authentication & Session</span><h1>{copy.title}</h1><p>{copy.detail}</p>{session.status === 'verification-required' && <div className="verification-box"><strong>MFA</strong><span>Doğrulama kodu bekleniyor.</span></div>}{loginAllowed && <button type="button" className="primary-button" onClick={onLogin}>Giriş yap</button>}</section></main>; }
function StatePanel({ state }: { state: Exclude<ViewState, 'success'> }) { const copy = { loading: ['Yükleniyor', 'İçerik güvenli şekilde hazırlanıyor.'], empty: ['Henüz içerik yok', 'Bu görünümde gösterilecek kayıt bulunmuyor.'], error: ['Bir sorun oluştu', 'İşlem tamamlanamadı. Tekrar deneyebilirsiniz.'], forbidden: ['Erişim izniniz yok', 'Bu kaynağa erişme yetkiniz bulunmuyor.'], 'not-found': ['Sayfa bulunamadı', 'İstenen kaynak mevcut değil veya erişilebilir değil.'] } as const; return <section className="state-panel" aria-live="polite"><h2>{copy[state][0]}</h2><p>{copy[state][1]}</p></section>; }

function WorkflowScreen({ screen, role }: { screen: ScreenDefinition; role: WebRole }) {
  if (role === 'instructor' && screen.href === '/instructor/trainings') return <InstructorAuthoringWorkspace />;
  if (role === 'instructor' && (screen.href === '/instructor/questions' || screen.href === '/instructor/assessments')) return <QuestionAssessmentWorkspace />;
  if (role === 'tenant_admin' && screen.href === '/admin/organization') return <OrganizationAdminView state="ready" organization={{ id: 'org-demo', name: 'Kurumsal Organizasyon', code: 'ORG', status: 'ACTIVE', companyCount: 2, departmentCount: 5, employeeCount: 128 }} companies={[{ id: 'company-1', name: 'Ana Şirket', code: 'AS', status: 'ACTIVE', departmentCount: 3, employeeCount: 94 }, { id: 'company-2', name: 'İştirak', code: 'IST', status: 'ACTIVE', departmentCount: 2, employeeCount: 34 }]} departmentsByCompany={{ 'company-1': [{ id: 'dep-1', name: 'Bilgi Teknolojileri', code: 'BT', status: 'ACTIVE', companyId: 'company-1', children: [{ id: 'dep-2', name: 'Altyapı', code: 'ALT', status: 'ACTIVE', companyId: 'company-1', children: [] }] }], 'company-2': [{ id: 'dep-4', name: 'Operasyon', code: 'OPS', status: 'ACTIVE', companyId: 'company-2', children: [] }] }} />;
  if (role === 'tenant_admin' && screen.href === '/admin/organization/personnel') return <PersonnelAdminView state="ready" employees={[{ id: 'e1', fullName: 'Ayşe Yılmaz', employeeNo: '1001', email: 'ayse@example.test', status: 'ACTIVE', companyName: 'Ana Şirket', departmentName: 'Bilgi Teknolojileri', positionName: 'Uzman', locationName: 'Merkez', accountState: 'LINKED' }, { id: 'e2', fullName: 'Mehmet Kaya', employeeNo: '1002', status: 'ACTIVE', companyName: 'İştirak', departmentName: 'Operasyon', positionName: 'Sorumlu', locationName: 'Saha', accountState: 'NOT_LINKED' }]} selected={{ id: 'e1', fullName: 'Ayşe Yılmaz', employeeNo: '1001', status: 'ACTIVE', companyName: 'Ana Şirket', departmentName: 'Bilgi Teknolojileri', positionName: 'Uzman', locationName: 'Merkez', accountState: 'LINKED' }} history={[{ id: 'h1', startedAt: '2025-01-01', endedAt: null, companyName: 'Ana Şirket', departmentName: 'Bilgi Teknolojileri', positionName: 'Uzman', locationName: 'Merkez' }]} />;
  if (role === 'tenant_admin' && screen.href === '/admin/organization/directory') return <GroupDirectoryAdminView state="ready" groups={[{ id: 'g1', name: 'BT Ekibi', type: 'MANUAL', status: 'ACTIVE', memberCount: 12 }, { id: 'g2', name: 'Yeni Başlayanlar', type: 'DYNAMIC', status: 'ACTIVE', memberCount: 8 }, { id: 'g3', name: 'Tüm Personel', type: 'SYSTEM', status: 'ACTIVE', memberCount: 128 }]} selectedGroup={{ id: 'g1', name: 'BT Ekibi', type: 'MANUAL', status: 'ACTIVE', memberCount: 12 }} members={[{ employeeId: 'e1', fullName: 'Ayşe Yılmaz', source: 'MANUAL', validFrom: '2026-01-01', validUntil: null }]} positions={[{ id: 'p1', name: 'Uzman', code: 'UZM', status: 'ACTIVE' }, { id: 'p2', name: 'Müdür', code: 'MDR', status: 'ACTIVE' }]} locations={[{ id: 'l1', name: 'Merkez', code: 'MRK', status: 'ACTIVE' }, { id: 'l2', name: 'Saha', code: 'SAH', status: 'ACTIVE' }]} />;
  if (role === 'tenant_admin' && screen.href === '/admin/organization/operations') return <OperationsAdminView state="ready" imports={[{ id: 'imp1', fileName: 'personel-2026-09.csv', status: 'REVIEW', rows: 128, warnings: 3 }]} integrations={[{ id: 'ad1', name: 'Kurumsal AD', type: 'AD_LDAP', status: 'CONNECTED', lastSyncAt: '2026-09-05 20:00' }, { id: 'erp1', name: 'İK ERP', type: 'HR_ERP', status: 'DEGRADED', error: 'Son senkron kısmi tamamlandı.' }]} audit={[{ id: 'a1', actor: 'admin@example.test', action: 'EMPLOYMENT_TRANSFER', occurredAt: '2026-09-05 19:42', entity: 'employee:e1', correlationId: 'corr-001' }]} audience={[{ type: 'DEPARTMENT', id: 'd1', label: 'Bilgi Teknolojileri', resolvedLearners: 18 }, { type: 'GROUP', id: 'g1', label: 'BT Ekibi', resolvedLearners: 12 }]} uniqueLearnerCount={22} overlapCount={8} />;
  const learner = role === 'learner';
  return <><header className="page-header"><div><span className="eyebrow">Ekran #{screen.id} · {roleLabels[role]}</span><h1>{screen.title}</h1><p>{screen.description}</p></div><span className="status-badge">{learner ? 'Sunucu yetkili' : 'Rol kapsamı'}</span></header><section className="content-card" aria-labelledby="workflow-state-title"><h2 id="workflow-state-title">Desteklenen durumlar</h2><div className="chip-row">{screen.workflowStates.map((state) => <span className="state-chip" key={state}>{state}</span>)}</div></section>{learner && <section className="content-card safety-card"><h2>Learner güvenlik sınırı</h2><p>Navigation yalnız sunum katmanıdır. Yetkilendirme sunucu tarafında yapılır; assessment answer key ve scoring secret istemci projection’ına dahil edilmez.</p></section>}</>;
}

function App() {
  const [role, setRole] = useState<WebRole>('learner');
  const [viewState, setViewState] = useState<ViewState>('success');
  const [session, setSession] = useState<SessionState>(() => sessionFromRuntime());
  const [href, setHref] = useState(defaultScreenFor('learner').href);
  const effectiveRole = canRenderProtectedShell(session) ? session.role : role;
  const nav = navForRole(effectiveRole);
  const currentScreen = screenFor(effectiveRole, href) ?? defaultScreenFor(effectiveRole);
 
  function navigate(nextHref: string) { setHref(screenFor(effectiveRole, nextHref)?.href ?? defaultScreenFor(effectiveRole).href); setViewState('success'); }
  if (!canRenderProtectedShell(session)) return <div className="public-shell"><a className="skip-link" href="#main-content">İçeriğe geç</a><header className="public-topbar"><div className="brand"><span className="brand-mark">K</span><div><strong>KAEP</strong><small>Kurumsal Eğitim</small></div></div></header><SessionPanel session={session} onLogin={() => setSession(sessionFromRuntime())} /></div>;
  return <div className="app-shell"><a className="skip-link" href="#main-content">İçeriğe geç</a><aside className="sidebar" aria-label="Ana navigasyon"><div className="brand"><span className="brand-mark">K</span><div><strong>KAEP</strong><small>Kurumsal Eğitim</small></div></div><nav>{nav.map((item) => <a className={item.href === currentScreen.href ? 'active' : ''} href={item.href} key={item.href} onClick={(event) => { event.preventDefault(); navigate(item.href); }}>{item.label}</a>)}</nav></aside><div className="workspace"><header className="topbar"><strong>{roleLabels[effectiveRole]}</strong><div className="state-switcher"><button type="button" className="link-button" onClick={() => { sessionStorage.clear(); setSession({ status: 'unauthenticated' }); }}>Çıkış</button></div></header><main id="main-content">{viewState === 'success' ? <WorkflowScreen screen={currentScreen} role={effectiveRole} /> : <StatePanel state={viewState} />}</main><nav className="mobile-nav" aria-label="Mobil navigasyon">{nav.slice(0, 4).map((item) => <a href={item.href} key={item.href} onClick={(event) => { event.preventDefault(); navigate(item.href); }}>{item.label}</a>)}</nav></div></div>;
}

createRoot(document.getElementById('root')!).render(<React.StrictMode><App /></React.StrictMode>);
